### ISSUE TITLE
After update: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by QaahirStewart** [nuxt-modules/icon#100]
After update getting this error with icons failing to load. Found where error is coming from. Fixed when removing ":.replace(/^i-/, ''))"

From changelog:
- const iconName = computed(() => (appConfig.nuxtIcon?.aliases || {})[props.name] || props.name)
+ const iconName = computed(() => ((appConfig.nuxtIcon?.aliases || {})[props.name] || props.name).replace(/^i-/, ''))

Console error:
Icon.vue:25  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at ReactiveEffect.fn (Icon.vue:25:97)
    at ReactiveEffect.run (chunk-BVQHDTV7.js:423:19)
    at get value [as value] (chunk-BVQHDTV7.js:1383:35)
    at Icon.vue:54:22
    at callWithErrorHandling (chunk-BVQHDTV7.js:1565:32)
    at ReactiveEffect.getter [as fn] (chunk-BVQHDTV7.js:3099:22)
    at ReactiveEffect.run (chunk-BVQHDTV7.js:423:19)
    at doWatch (chunk-BVQHDTV7.js:3195:26)
    at watch (chunk-BVQHDTV7.js:3050:10)
    at setup (Icon.vue:54:1)

**Comment by Kashalls** [comment]
Seeing this on a clean install, `npx nuxi init` + `npm i nuxt-icon`

**Comment by Martacus** [comment]
I've got the same problem, i there a fix other than the open pr?

Maybe going to an older version?
