### ISSUE TITLE
Cannot restart nuxt:  The "name" argument must be specified     

### ISSUE THREAD

**Issue by craigmpetersou** [nuxt-modules/icon#65]
New install of the module

Console log:
```
 ERROR  Cannot restart nuxt:  The "name" argument must be specified                                                                                                                                  20:56:47

  at new NodeError (node:internal/errors:399:5)
  at Performance.mark (node:internal/perf/performance:125:13)
  at normalizedModule (node_modules/nuxt-icon/node_modules/@nuxt/kit/dist/index.mjs:168:30)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:435:15)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2253:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6802:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6731:10)
```

nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
      modules: [
            '@nuxtjs/tailwindcss',
            '@pinia/nuxt',
            'nuxt-icon',
      ],
      css: ['@/assets/css/main.css',],

})
```

**Comment by ineshbose** [comment]
Are you on Node.js v19? Related: https://github.com/nuxt/nuxt/issues/19682
